[package]
name = "gnss2tec-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["clock"] }
clap = { version = "4.5.49", features = ["derive"] }
ctrlc = "3.5.0"
fs2 = "0.4.3"
serialport = "4.8.1"
